### ISSUE TITLE
Site Engineering

### ISSUE THREAD

**Issue by suschuk24** [TeamJeanGrey/ultimate-movie-search#1]
-Create HTML and CSS framework

- Discuss and place basic style and page layout elements

- Color Scheme

-Attach proper files (API tags, js, css, etc)

**Comment by suschuk24** [comment]
Make it about the actor. User enters a search (predictive text) and returns different dynamic html elements.

-top 5 movies (imdb api) by popularity

--generates cards with links to corresponding imdb page

-top 5 rotten tomato (rotten tomato api) by score

--generates cards with links to corresponding rotten tomato

-Link to trailer latest movie (YouTube API) by release date

--link with preview

**make sure links to other page open in new tab.                       "_blank"

use mobile first design, dark theme

**Comment by suschuk24** [comment]
Still need to edit page responsiveness for screen sizes.

**Comment by K2gees** [comment]
Screen is responsive and top movies are displayed on landing page.  Site focus was shifted to movies instead of an actor to broaden search.
