### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by suschuk24** [TeamJeanGrey/ultimate-movie-search#4]
-create variables that coincide with  HTML page for dynamic elements 

-create functions to pull from API data to search by various keywords/categories (genera, rating, actor, movie title, etc?)

-give user option to save search results using local storage

**Comment by suschuk24** [comment]
basic JS is done, still need to complete the appendchild functions and local storage functions. Waiting to get API endpoints finished before continuing with javascript.

**Comment by K2gees** [comment]
All issues with javascript addressed.
